// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCoaching.Infrastructure.Persistence;

#nullable disable

namespace SmartCoaching.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625152009_ConvertWorkoutToJson")]
    partial class ConvertWorkoutToJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCoaching.Domain.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentTrainingRoutine")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Expectations")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneralDietNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HasTrackedMacros")
                        .HasColumnType("text");

                    b.Property<string>("HasWorkedWithCoach")
                        .HasColumnType("text");

                    b.Property<string>("HearAboutUs")
                        .HasColumnType("text");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastProgramNotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongTermGoal")
                        .HasColumnType("text");

                    b.Property<string>("MainReason")
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("OutsidePhysicalActivity")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ShortTermGoal")
                        .HasColumnType("text");

                    b.Property<double?>("StartingWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TargetCalories")
                        .HasColumnType("numeric");

                    b.Property<int>("TargetSteps")
                        .HasColumnType("integer");

                    b.Property<string>("TrainingHistory")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.DietMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Fats")
                        .HasColumnType("integer");

                    b.Property<string>("Foods")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Protein")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("DietMeals");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.ProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("text");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<string>("BackPhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("CoachFeedback")
                        .HasColumnType("text");

                    b.Property<decimal>("ConsumedCalories")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrontPhotoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsWorkoutCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SidePhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("TakenSteps")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.Athlete", b =>
                {
                    b.HasOne("SmartCoaching.Domain.Entities.Coach", "Coach")
                        .WithMany("Athletes")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SmartCoaching.Domain.Entities.WorkoutExercise", "WorkoutExercises", b1 =>
                        {
                            b1.Property<Guid>("AthleteId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("DayName")
                                .IsRequired();

                            b1.Property<string>("ExerciseName")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Notes");

                            b1.Property<int>("OrderIndex");

                            b1.Property<string>("Reps")
                                .IsRequired();

                            b1.Property<int>("RestTimeInSeconds");

                            b1.Property<int>("Sets");

                            b1.HasKey("AthleteId", "__synthesizedOrdinal");

                            b1.ToTable("Athletes");

                            b1
                                .ToJson("WorkoutExercises")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.Navigation("Coach");

                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.DietMeal", b =>
                {
                    b.HasOne("SmartCoaching.Domain.Entities.Athlete", "Athlete")
                        .WithMany("DietMeals")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.ProgressLog", b =>
                {
                    b.HasOne("SmartCoaching.Domain.Entities.Athlete", "Athlete")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.Athlete", b =>
                {
                    b.Navigation("DietMeals");

                    b.Navigation("ProgressLogs");
                });

            modelBuilder.Entity("SmartCoaching.Domain.Entities.Coach", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
